name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'web/**'
      - '.github/workflows/deploy-gh-pages.yml'
  workflow_dispatch:

permissions:
  contents: write   # para push no branch gh-pages

defaults:
  run:
    working-directory: web   # <- seu app está em /web

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build + Deploy (angular-cli-ghpages)
        env:
          CI: true
        run: |
          npx ng deploy \
            --base-href=/web2/ \
            --branch=gh-pages \
            --name="github-actions[bot]" \
            --email="github-actions[bot]@users.noreply.github.com" \
            --repo=https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/AngeloPre/web2.git \
            --no-silent